### ISSUE TITLE
Features differ after rerun

### ISSUE THREAD

**Issue by peterneher** [oncoray/mirp#43]
I calculate features using the following command:
`mirp.extract_features(image=parameter_map_file_name, 
                                            mask=parcellation_file_name, 
                                            base_discretisation_method="fixed_bin_number", 
                                            base_discretisation_n_bins=32, 
                                            export_features=True, 
                                            num_cpus=1)`

At every run, the following two features have slightly different values (~0.5-1%):
1. morph_moran_i
2. morph_geary_c

All other features are ok, at least with a tolerance of 1.0e-10.

**Comment by alexzwanenburg** [comment]
Thanks for checking! The original implementations of Moran's I and Geary's C measures have high computational complexity. Because of this, `mirp` implements an approximation by computing multiple values of each feature on smaller *random* subsets of voxels, and then averaging these.

If the original (deterministic) implementation is desired, you can add `no_approximation = True` as argument to your function call.

**Comment by peterneher** [comment]
Is it possible to fix the seed for this randomness?

**Comment by alexzwanenburg** [comment]
Yes. The current implementation relies on [np.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html). It may be possible to set [np.random.seed](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html) externally before calling `mirp`.

However, this may not be cleanest solution from the user perspective, and it may be preferable to move `mirp` to Generator-based randomisation for functions and methods that rely on randomisation.
